// +build darwin

// Code generated by "stringer -type=Errors"; DO NOT EDIT.

package fsedata

import "fmt"

const _Errors_name = "NoErrorErrorNoWatchPointErrorWrongWatchPointErrorNoDirWatchPoint"

var _Errors_index = [...]uint8{0, 7, 24, 44, 64}

func (i Errors) String() string {
	if i < 0 || i >= Errors(len(_Errors_index)-1) {
		return fmt.Sprintf("Errors(%d)", i)
	}
	return _Errors_name[_Errors_index[i]:_Errors_index[i+1]]
}
