// +build darwin

// Code generated by "stringer -type=EventFlags"; DO NOT EDIT.

package fsedata

import "fmt"

const _EventFlags_name = "MustScanSubDirsUserDroppedKernelDroppedEventIDsWrappedHistoryDoneRootChangedMountUnmountItemCreatedItemRemovedItemInodeMetaModItemRenamedItemModifiedItemFinderInfoModItemChangeOwnerItemXattrModItemIsFileItemIsDirItemIsSymlink"

var _EventFlags_map = map[EventFlags]string{
	1:      _EventFlags_name[0:15],
	2:      _EventFlags_name[15:26],
	4:      _EventFlags_name[26:39],
	8:      _EventFlags_name[39:54],
	16:     _EventFlags_name[54:65],
	32:     _EventFlags_name[65:76],
	64:     _EventFlags_name[76:81],
	128:    _EventFlags_name[81:88],
	256:    _EventFlags_name[88:99],
	512:    _EventFlags_name[99:110],
	1024:   _EventFlags_name[110:126],
	2048:   _EventFlags_name[126:137],
	4096:   _EventFlags_name[137:149],
	8192:   _EventFlags_name[149:166],
	16384:  _EventFlags_name[166:181],
	32768:  _EventFlags_name[181:193],
	65536:  _EventFlags_name[193:203],
	131072: _EventFlags_name[203:212],
	262144: _EventFlags_name[212:225],
}

func (i EventFlags) String() string {
	if str, ok := _EventFlags_map[i]; ok {
		return str
	}
	return fmt.Sprintf("EventFlags(%d)", i)
}
